# Generated by Django 2.1.3 on 2024-12-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=None)),
                ('estudiante', models.IntegerField(default=None)),
                ('fechaEmision', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.CharField(max_length=50)),
            ],
        ),
    ]
